### ISSUE TITLE
Failed to activate the language-ballerina package

### ISSUE THREAD

**Issue by Gayan42** [ballerina-lang/plugin-atom#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-ballerina](https://github.com/ballerinalang/plugin-atom) package 0.8.8

### Stack Trace

Failed to activate the language-ballerina package

```
At Cannot read property 'realPath' of undefined

TypeError: Cannot read property 'realPath' of undefined
    at LanguageBallerina.activate (/packages/language-ballerina/lib/language-ballerina.js:92:82)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:968:31
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:246:26)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:16.5.0 language-ballerina:parse (div.lines)
```

### Non-Core Packages

```
language-ballerina 0.8.8 
```

**Comment by uthaiyashankar** [comment]
Postponing and moving the repo to attic.
